// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public static partial class Reducer
	{
		public delegate void UpdatePlayerPositionHandler(ReducerEvent reducerEvent, SpacetimeDB.Types.StdbVector3 position, float direction, bool moving);
		public static event UpdatePlayerPositionHandler OnUpdatePlayerPositionEvent;

		public static void UpdatePlayerPosition(SpacetimeDB.Types.StdbVector3 position, float direction, bool moving)
		{
			var _argArray = new object[] {position, direction, moving};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "update_player_position",
				args = _argArray,
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "update_player_position")]
		public static bool OnUpdatePlayerPosition(ClientApi.Event dbEvent)
		{
			if(OnUpdatePlayerPositionEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).UpdatePlayerPositionArgs;
				OnUpdatePlayerPositionEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(SpacetimeDB.Types.StdbVector3)args.Position
					,(float)args.Direction
					,(bool)args.Moving
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "update_player_position")]
		public static void UpdatePlayerPositionDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new UpdatePlayerPositionArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.Types.StdbVector3.GetAlgebraicType(), reader);
			args.Position = (SpacetimeDB.Types.StdbVector3)(args_0_value);
			var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.F32), reader);
			args.Direction = args_1_value.AsF32();
			var args_2_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.Bool), reader);
			args.Moving = args_2_value.AsBool();
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.UpdatePlayerPosition, "update_player_position", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), Address.From(dbEvent.CallerAddress.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class UpdatePlayerPositionArgsStruct
	{
		public SpacetimeDB.Types.StdbVector3 Position;
		public float Direction;
		public bool Moving;
	}

}
